"""Golden tests for the reference sequential acceptance verifier (plan todo 6).

The reference verifier is the ground truth every other verifier is checked
against, so its tests use hand-computed expectations only — never values
generated by the implementation itself.
"""

from __future__ import annotations

import pytest
import torch

from familydraft.verify.reference import verify_chain_greedy, verify_chain_sample

# Tiny fixed vocabulary for all goldens.
V = 4


def dist(*values: float) -> torch.Tensor:
    return torch.tensor(list(values), dtype=torch.float32)


def norm(*values: float) -> torch.Tensor:
    t = torch.tensor(list(values), dtype=torch.float32)
    return t / t.sum()


def test_greedy_full_accept_and_bonus() -> None:
    # Given target argmax sequence [1, 2, 3] and a final-position argmax 0
    target = [
        dist(0.1, 0.9, 0.0, 0.0),
        dist(0.0, 0.1, 0.8, 0.1),
        dist(0.0, 0.0, 0.2, 0.8),
        dist(0.7, 0.1, 0.1, 0.1),
    ]
    # When the draft matches every argmax
    verdict = verify_chain_greedy(target, [1, 2, 3])
    # Then everything is accepted and the bonus is the next target argmax
    assert verdict.accepted_tokens == (1, 2, 3)
    assert verdict.accept_length == 3
    assert verdict.bonus_token == 0


def test_greedy_immediate_reject() -> None:
    # all three positions are scored by the target even though the draft
    # dies at position 0 (verification always evaluates the whole chain)
    target = [
        dist(0.0, 0.1, 0.9, 0.0),
        dist(1.0, 0.0, 0.0, 0.0),
        dist(0.0, 0.0, 1.0, 0.0),
    ]
    verdict = verify_chain_greedy(target, [3, 0])
    assert verdict.accepted_tokens == ()
    assert verdict.accept_length == 0
    assert verdict.bonus_token == 2


def test_greedy_mid_chain_reject() -> None:
    target = [
        dist(0.0, 0.9, 0.1, 0.0),
        dist(0.0, 0.2, 0.7, 0.1),
        dist(1.0, 0.0, 0.0, 0.0),
        dist(0.0, 1.0, 0.0, 0.0),
    ]
    verdict = verify_chain_greedy(target, [1, 3, 0])
    assert verdict.accepted_tokens == (1,)
    assert verdict.accept_length == 1
    assert verdict.bonus_token == 2


def test_greedy_empty_draft_gives_bonus_only() -> None:
    target = [dist(0.0, 0.0, 0.3, 0.7)]
    verdict = verify_chain_greedy(target, [])
    assert verdict.accepted_tokens == ()
    assert verdict.accept_length == 0
    assert verdict.bonus_token == 3


def test_greedy_requires_enough_distributions() -> None:
    with pytest.raises(ValueError, match="at least"):
        verify_chain_greedy([dist(0.0, 1.0, 0.0, 0.0)], [1, 2])


def test_sample_guaranteed_accept_then_onehot_bonus() -> None:
    # p >= q on the drafted token -> acceptance ratio >= 1 -> always accept
    p0 = norm(0.5, 0.5, 0.0, 0.0)
    q0 = norm(0.4, 0.6, 0.0, 0.0)
    p1 = norm(0.5, 0.5, 0.0, 0.0)
    q1 = norm(0.6, 0.4, 0.0, 0.0)
    bonus_dist = norm(0.0, 0.0, 1.0, 0.0)
    gen = torch.Generator().manual_seed(7)
    verdict = verify_chain_sample(
        [p0, p1, bonus_dist], [q0, q1], [0, 0], generator=gen
    )
    assert verdict.accepted_tokens == (0, 0)
    assert verdict.accept_length == 2
    assert verdict.bonus_token == 2


def test_sample_forced_reject_with_onehot_residual() -> None:
    # Given target puts zero mass on the drafted token
    p0 = norm(1.0, 0.0, 0.0, 0.0)
    q0 = norm(0.25, 0.25, 0.25, 0.25)
    filler = norm(0.25, 0.25, 0.25, 0.25)
    gen = torch.Generator().manual_seed(11)
    # When the draft proposed token 1, rejection is forced (ratio 0);
    # the second distribution is required by scoring but never reached
    verdict = verify_chain_sample([p0, filler], [q0], [1], generator=gen)
    # Then nothing is accepted and the residual norm(clamp(p0-q0)) is one-hot
    # on token 0, so the bonus is deterministic
    assert verdict.accepted_tokens == ()
    assert verdict.accept_length == 0
    assert verdict.bonus_token == 0


def test_sample_rejects_unnormalized_distributions() -> None:
    bad = dist(0.5, 0.2, 0.1, 0.1)
    filler = norm(0.25, 0.25, 0.25, 0.25)
    gen = torch.Generator().manual_seed(1)
    with pytest.raises(ValueError, match="summing to 1"):
        verify_chain_sample([bad, filler], [filler], [0], generator=gen)


def test_sample_token_zero_marginal_matches_target() -> None:
    # Distribution-preservation probe: the first output token of speculative
    # sampling must be marginally distributed as the target's first position,
    # regardless of the (different) draft distribution. Chi-square on 20k
    # samples, df=4, alpha=0.05 critical value 9.488.
    p0 = norm(0.35, 0.25, 0.20, 0.15, 0.05)
    q0 = norm(0.10, 0.10, 0.20, 0.30, 0.30)
    filler = norm(0.2, 0.2, 0.2, 0.2, 0.2)

    gen = torch.Generator().manual_seed(42)
    counts = torch.zeros(5, dtype=torch.int64)
    n = 20_000
    for _ in range(n):
        draft_token = int(torch.multinomial(q0, 1, generator=gen))
        verdict = verify_chain_sample(
            [p0, filler], [q0], [draft_token], generator=gen
        )
        first = verdict.accepted_tokens[0] if verdict.accept_length else verdict.bonus_token
        counts[first] += 1

    expected = p0 * n
    chi2 = float((((counts - expected) ** 2) / expected).sum())
    assert chi2 < 9.488, f"first-output-token distribution drifted from target: chi2={chi2}"
